### ISSUE TITLE
Add phpunit to OIL parser

### ISSUE THREAD

**Issue by cpantel** [ciaa/firmware.modules.rtos#12]
In order to refactor and complete the OIL parser add unit testing

**Comment by mcerdeiro** [comment]
La issue debería ir al repo de firmware.

En el commit comment usas ciaa/Firmware#nunero para te la reconozca.

Saludos
Am 21.06.2015 19:04 schrieb "cpantel" <notifications@github.com>:

**Comment by mcerdeiro** [comment]
issues shall be created in https://github.com/ciaa/Firmware/issues
