### ISSUE TITLE
bug due to index repeated in Interrupt sources definition for MK60F12

### ISSUE THREAD

**Issue by apermingeat** [ciaa/firmware.modules.rtos#19]
Index 84 is repeated in Interrupt sources definition for MK60F12, in Os_Internal_Arch_Cfg.c.php for cortexM4.

**Comment by gmuro** [comment]
Ale.
Las issues las manejamos todas por Firmware. Luego para referenciar tenes que poner 
ciaa/Firmware#<numeroDeIssue>

**Comment by apermingeat** [comment]
Ha OK!
Entonces la cargo como un Issue de Firmware y la borro de acá?

**Comment by gmuro** [comment]
exacto!

**Comment by apermingeat** [comment]
This issue is moved to Firmware repository. Now is in ciaa/Firmware#339
