### ISSUE TITLE
The attribute TICKSPERBASE does not work

### ISSUE THREAD

**Issue by gmuro** [ciaa/firmware.modules.rtos#9]
The TICKSPERBASE attribute specifies the number of ticks required to reach a counter-specific unit. The interpretation is implementation-specific.
(OIL: OSEK Implementation Language Version 2.5. 3.2.5.2)

**Comment by mcerdeiro** [comment]
Hi Gus, the tickets shall be created in https://github.com/ciaa/Firmware/issues. But anyway what do we have to do with this ticket? our osek does nothing with this value... :)

**Comment by gmuro** [comment]
Done. Moved to https://github.com/ciaa/Firmware/issues

**Comment by mcerdeiro** [comment]
moved to ciaa/Firmware#284
